version: '3.8'

services:
  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: jiachu_app
    restart: always
    working_dir: /var/www/
    volumes:
      - ./src:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
      XDEBUG_MODE: "debug"
      XDEBUG_CONFIG: "client_host=host.docker.internal"
    networks:
      - jiachu_network

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    container_name: jiachu_nginx
    restart: unless-stopped
    ports:
      - "97${PORT_NUMBER}:80"
    volumes:
      - ./src:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - jiachu_network
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: jiachu_mysql
    restart: always
    environment:
      MYSQL_DATABASE: jiachu
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/mysql/my.cnf:/etc/my.cnf
    ports:
      - "95${PORT_NUMBER}:3306"
    networks:
      - jiachu_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: jiachu_phpmyadmin
    restart: unless-stopped
    ports:
      - "96${PORT_NUMBER}:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    networks:
      - jiachu_network
    depends_on:
      - mysql

networks:
  jiachu_network:
    driver: bridge

volumes:
  mysql_data: 